<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="testAll" duration-ms="46" started-at="2018-11-29T02:34:44Z" finished-at="2018-11-29T02:34:44Z">
    <groups>
      <group name="enTest">
        <method signature="TestDBConnection.runOtherTest1()[pri:0, instance:com.guoxin.demo.TestDBConnection@af1cf6]" name="runOtherTest1" class="com.guoxin.demo.TestDBConnection"/>
      </group> <!-- enTest -->
    </groups>
    <test name="case1" duration-ms="46" started-at="2018-11-29T02:34:44Z" finished-at="2018-11-29T02:34:44Z">
      <class name="com.guoxin.demo.TestDBConnection">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.guoxin.demo.TestDBConnection@af1cf6]" name="setUp" is-config="true" duration-ms="12" started-at="2018-11-29T10:34:44Z" finished-at="2018-11-29T10:34:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="befClass()[pri:0, instance:com.guoxin.demo.TestDBConnection@af1cf6]" name="befClass" is-config="true" duration-ms="0" started-at="2018-11-29T10:34:44Z" finished-at="2018-11-29T10:34:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- befClass -->
        <test-method status="FAIL" signature="runOtherTest6()[pri:0, instance:com.guoxin.demo.TestDBConnection@af1cf6]" name="runOtherTest6" duration-ms="1" started-at="2018-11-29T10:34:44Z" finished-at="2018-11-29T10:34:44Z">
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
	at com.guoxin.demo.TestDBConnection.runOtherTest6(TestDBConnection.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:74)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runOtherTest6 -->
        <test-method status="PASS" signature="runOtherTest1()[pri:0, instance:com.guoxin.demo.TestDBConnection@af1cf6]" name="runOtherTest1" duration-ms="0" started-at="2018-11-29T10:34:44Z" finished-at="2018-11-29T10:34:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runOtherTest1 -->
        <test-method status="PASS" signature="runOtherTest3()[pri:0, instance:com.guoxin.demo.TestDBConnection@af1cf6]" name="runOtherTest3" duration-ms="0" started-at="2018-11-29T10:34:44Z" finished-at="2018-11-29T10:34:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runOtherTest3 -->
        <test-method status="SKIP" signature="runOtherTest7()[pri:0, instance:com.guoxin.demo.TestDBConnection@af1cf6]" name="runOtherTest7" duration-ms="0" started-at="2018-11-29T10:34:44Z" depends-on-methods="com.guoxin.demo.TestDBConnection.runOtherTest6" finished-at="2018-11-29T10:34:44Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDBConnection.runOtherTest7()[pri:0, instance:com.guoxin.demo.TestDBConnection@af1cf6] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDBConnection.runOtherTest7()[pri:0, instance:com.guoxin.demo.TestDBConnection@af1cf6] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:74)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runOtherTest7 -->
      </class> <!-- com.guoxin.demo.TestDBConnection -->
    </test> <!-- case1 -->
  </suite> <!-- testAll -->
</testng-results>
